// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Command command
//
// swagger:model Command
type Command struct {

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// device Id
	DeviceID int64 `json:"deviceId,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this command
func (m *Command) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this command based on context it is used
func (m *Command) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Command) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Command) UnmarshalBinary(b []byte) error {
	var res Command
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
