// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Driver driver
//
// swagger:model Driver
type Driver struct {

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// unique Id
	UniqueID string `json:"uniqueId,omitempty"`
}

// Validate validates this driver
func (m *Driver) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this driver based on context it is used
func (m *Driver) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Driver) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Driver) UnmarshalBinary(b []byte) error {
	var res Driver
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
