// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Geofence geofence
//
// swagger:model Geofence
type Geofence struct {

	// area
	Area string `json:"area,omitempty"`

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// calendar Id
	CalendarID int64 `json:"calendarId,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this geofence
func (m *Geofence) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this geofence based on context it is used
func (m *Geofence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Geofence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Geofence) UnmarshalBinary(b []byte) error {
	var res Geofence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
