// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReportTrips report trips
//
// swagger:model ReportTrips
type ReportTrips struct {

	// in knots
	AverageSpeed float64 `json:"averageSpeed,omitempty"`

	// device Id
	DeviceID int64 `json:"deviceId,omitempty"`

	// device name
	DeviceName string `json:"deviceName,omitempty"`

	// in meters
	Distance float64 `json:"distance,omitempty"`

	// driver name
	DriverName string `json:"driverName,omitempty"`

	// driver unique Id
	DriverUniqueID int64 `json:"driverUniqueId,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// end address
	EndAddress string `json:"endAddress,omitempty"`

	// end lat
	EndLat float64 `json:"endLat,omitempty"`

	// end lon
	EndLon float64 `json:"endLon,omitempty"`

	// in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
	// Format: date-time
	EndTime strfmt.DateTime `json:"endTime,omitempty"`

	// in knots
	MaxSpeed float64 `json:"maxSpeed,omitempty"`

	// in liters
	SpentFuel float64 `json:"spentFuel,omitempty"`

	// start address
	StartAddress string `json:"startAddress,omitempty"`

	// start lat
	StartLat float64 `json:"startLat,omitempty"`

	// start lon
	StartLon float64 `json:"startLon,omitempty"`

	// in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
	// Format: date-time
	StartTime strfmt.DateTime `json:"startTime,omitempty"`
}

// Validate validates this report trips
func (m *ReportTrips) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReportTrips) validateEndTime(formats strfmt.Registry) error {
	if swag.IsZero(m.EndTime) { // not required
		return nil
	}

	if err := validate.FormatOf("endTime", "body", "date-time", m.EndTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ReportTrips) validateStartTime(formats strfmt.Registry) error {
	if swag.IsZero(m.StartTime) { // not required
		return nil
	}

	if err := validate.FormatOf("startTime", "body", "date-time", m.StartTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this report trips based on context it is used
func (m *ReportTrips) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReportTrips) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportTrips) UnmarshalBinary(b []byte) error {
	var res ReportTrips
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
