// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Calendar calendar
//
// swagger:model Calendar
type Calendar struct {

	// attributes
	Attributes interface{} `json:"attributes,omitempty"`

	// base64 encoded in iCalendar format
	Data string `json:"data,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this calendar
func (m *Calendar) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this calendar based on context it is used
func (m *Calendar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Calendar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Calendar) UnmarshalBinary(b []byte) error {
	var res Calendar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
